# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Teable systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ teable_identifier }}.service"
  register: teable_service_stat

- name: Uninstall Teable systemd services and files
  when: teable_service_stat.stat.exists | bool
  block:
    - name: Ensure Teable systemd service is stopped
      ansible.builtin.service:
        name: "{{ teable_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Teable systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ teable_identifier }}.service"
        state: absent

    - name: Ensure Teable support files do not exist
      ansible.builtin.file:
        path: "{{ teable_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Teable local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ teable_data_path }}"
      register: teable_data_path_deletion_result
      changed_when: teable_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Teable base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ teable_base_path }}"
      register: teable_base_path_deletion_result
      changed_when: teable_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Teable container network does not exist
      when: teable_container_network_deletion_enabled
      block:
        - name: Ensure Teable container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ teable_container_network }}"
            state: absent
          register: teable_network_deletion_result

        - name: Ensure Teable container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ teable_container_network }}
          register: teable_network_deletion_result
          changed_when: teable_container_network in teable_network_deletion_result.stdout

- name: Check existence of Teable local data path
  ansible.builtin.stat:
    path: "{{ teable_data_path }}"
  register: teable_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining Teable local data path
  when: teable_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Teable instance has been removed, some old data remains in `" + teable_data_path + "`. Feel free to delete it."
        ]
      }}
