# SPDX-FileCopyrightText: 2026 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    force: true
driver:
  name: docker
platforms:
  - name: teable-${MOLECULE_DISTRO:-ubuntu2604}-default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
  inventory:
    group_vars:
      all:
        # Helper variables
        teable_debug_service_enabled: false

        # Variables for Teable
        teable_uid: 0
        teable_gid: 0
        teable_scheme: http
        teable_hostname: localhost
        teable_container_labels_traefik_enabled: false
        teable_container_http_host_bind_port: 3000
        teable_environment_variables_secret_key: secret
        teable_systemd_docker_base_timeout_sec: "5m"

        # Variables required for Teable to connect to the Postgres database
        teable_database_hostname: "{{ postgres_connection_hostname }}"
        teable_database_port: "{{ postgres_connection_port }}"
        teable_database_username: my_database_username
        teable_database_password: my_database_password
        teable_database_name: teable
        teable_systemd_required_services_list_auto: |
          {{
            (['postgres.service'])
          }}

        # Variables for Postgres
        postgres_uid: 1000
        postgres_gid: 1000
        postgres_connection_password: postgres_password
        postgres_container_network: "{{ teable_container_network }}"
        postgres_managed_databases: |
          {{
            [{
              'name': teable_database_name,
              'username': teable_database_username,
              'password': teable_database_password,
            }]
          }}

        # Variables required for Teable to connect to the Valkey data-store
        teable_redis_hostname: "{{ valkey_identifier }}"
        teable_container_additional_networks_custom:
          - "{{ valkey_container_network }}"
        teable_systemd_required_services_list_custom:
          - "{{ valkey_identifier }}.service"

        # Variables for Valkey
        valkey_uid: 1000
        valkey_gid: 1000
        valkey_arch: amd64
  env:
    # Workaround for https://github.com/ansible/molecule/issues/4391
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles
scenario:
  # See: https://docs.ansible.com/projects/molecule/configuration/?h=test_sequence#scenario
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # Disable idempotence test for now due to ansible-role-postgres
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
