# SPDX-FileCopyrightText: 2026 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    force: true
driver:
  name: docker
platforms:
  - name: infisical-${MOLECULE_DISTRO:-ubuntu2604}-default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
  inventory:
    group_vars:
      all:
        # Helper variables
        infisical_debug_service_enabled: false

        # Variables for Infisical
        infisical_uid: 1000
        infisical_gid: 1000
        infisical_scheme: http
        infisical_hostname: localhost
        infisical_container_labels_traefik_enabled: false
        infisical_container_http_host_bind_port: 8080
        infisical_environment_variables_encryption_key: 0fe35784ccbe01ef20c4fd4b07cc8503
        infisical_environment_variables_auth_secret: ZM1Lt/TGxQGBCFA9l0mm58EMY/g81DYLvXBfvhfdp0E=
        infisical_environment_variables_site_url: https://localhost:8080
        infisical_systemd_docker_base_timeout_sec: "5m"

        # Variables required for Infisical to connect to the Postgres database
        infisical_database_hostname: "{{ postgres_connection_hostname }}"
        infisical_database_port: "{{ postgres_connection_port }}"
        infisical_database_username: my_database_username
        infisical_database_password: my_database_password
        infisical_database_name: infisical
        infisical_systemd_required_services_list_auto: |
          {{
            (['postgres.service'])
          }}

        # Variables for Postgres
        postgres_uid: 1000
        postgres_gid: 1000
        postgres_connection_password: postgres_password
        postgres_container_network: "{{ infisical_container_network }}"
        postgres_managed_databases: |
          {{
            [{
              'name': infisical_database_name,
              'username': infisical_database_username,
              'password': infisical_database_password,
            }]
          }}

        # Variables required for Infisical to connect to the Valkey data-store
        infisical_redis_hostname: "{{ valkey_identifier }}"
        infisical_container_additional_networks_custom:
          - "{{ valkey_container_network }}"
        infisical_systemd_required_services_list_custom:
          - "{{ valkey_identifier }}.service"

        # Variables for Valkey
        valkey_uid: 1000
        valkey_gid: 1000
        valkey_arch: amd64
  env:
    # Workaround for https://github.com/ansible/molecule/issues/4391
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles
scenario:
  # See: https://docs.ansible.com/projects/molecule/configuration/?h=test_sequence#scenario
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # Disable idempotence test for now due to ansible-role-postgres
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
