# SPDX-FileCopyrightText: 2026 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Prepare Teable Molecule tests
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Ensure apt cache is updated for Teable Molecule tests preparation
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Ensure required packages are installed for Teable Molecule tests preparation
      ansible.builtin.package:
        name:
          - python3-requests
        state: present

    - name: Ensure Docker is installed for Teable Molecule tests preparation
      ansible.builtin.include_role:
        name: ansible-role-docker
      vars:
        docker_daemon_options:
          storage-driver: vfs
